### ISSUE TITLE
Real time reloading for writing APIs and seeing changes in real time.

### ISSUE THREAD

**Issue by mindey** [firstopinion/endpoints#57]
### Real time reloading

To reload the server on every change in files of the directory, you may find [entr](http://entrproject.org) convenient, e.g.:

    $ ls -d * | entr sh -c "killall endpoints; endpoints --prefix=mycontroller --host=localhost:8000 &"

Could add this or something comparable to readme.

**Comment by Jaymon** [comment]
We mostly use tests that start and stop the server on each test run, so we've never investigated how to do this, but I think this is a great solution for this problem and I had never heard of `entr` before. I've updated the readme. Thanks
